### ISSUE TITLE
Authorization Issue

### ISSUE THREAD

**Issue by ZNevzz** [frcrceinterns/PMS_FINAL_REPO#15]
@Jugal69 
Since **authorization** has been done using Controller name in database, the user who is able to _read_ but not _write_ data , now won't be able to _read_ data too. Since both _read_ and _write_ operations are mapped with controller name.

The change in **CheckRoleServiceImpl** method is : 
1. instead of _function_name_,  _function_url_ will contain the authorization string.
2. all the mappings are same as mentioned in Work Breakdown Structure - Sheet 1 **Constants** table.

**Comment by LeonDsouza** [comment]
I now have the latest copy of the project.However, even after admin login i cannot access email page, upload csv page or any page.It redirects me to 403

**Comment by ZNevzz** [comment]
If you are able to spot the checkRoleService method call, you will be able to trace which url has been hardcoded in the method. This hardcoded url should be placed in your _function_url_ of your database table

**Comment by ZNevzz** [comment]
This will be eventually refactored towards the end of development schedule
