### ISSUE TITLE
Event Calendar 

### ISSUE THREAD

**Issue by ZNevzz** [frcrceinterns/PMS_FINAL_REPO#31]
What was planned : 
1. A form : to add event details. This data will be stored in database and retrieved in calendar
2. A java code : to retrieve events in month wise fashion
3. A calendar to display events month wise

What has been performed:
1. Form which adds data to database table.
2. Controller which fetches this table data and returns according to month selected, which would have been used in calendar
3. A Calendar, which uses google calendar of a gmail account. Events can be added, shifted, etc. This data is stored wrt to the gmail account mentioned.

1 has been performed by @RashmiSri 
2 has been performed by @darshgup139
3 has been performed by @Oneil1995 

Now 1 and 2 can work together , but not with 3

3 can work alone easily, but risk of attaching gmail account.

So i request all team members, to please give your review about the situation.

**Comment by darshgup139** [comment]
If you find it risky then do not keep it..Nevzz

**Comment by LeonDsouza** [comment]
Adarsh and Rashmi's code can work in combo but front end is missing or has not been done. So now we have to decide between front end stability and front end abscence! :thinking_face:

**Comment by RashmiSri** [comment]
Adding and viewing is a great and convenient functionality. Let it be there for at least it'll be able to display events in a month on querying, if not in the form of a calendar. Combining front end with this drags in a person's gmail account , then we need not use this front end for events display

**Comment by Crystal21** [comment]
how is the google calendar going to work with the DB??

**Comment by ZNevzz** [comment]
The Google calendar doesn't work with the DB. We can, but it will take a lot of time, which we already don't have

**Comment by pankajsankpal** [comment]
gmail calendar seems  contradict to 1st and 2nd module..
we can add a good UI for the 1st and 2nd part (though it'll  not look like a calendar actually , but at least our purpose to show the event month wise can be achieve) .

**Comment by ZNevzz** [comment]
Thus by popular vote we have decided to not include google api supported calendar
