### ISSUE TITLE
Profile tab in Profile page

### ISSUE THREAD

**Issue by ZNevzz** [frcrceinterns/PMS_FINAL_REPO#32]
Only Student and StudentTPC have details mentioned in personal and professional tables in database.
So I suggest we remove the Profile tab from all the other actor UIs.
We already display username at top right of screen, where logout option is there.

**Comment by darshgup139** [comment]
If there no data to be displayed in Profile Tab then remove it for other users...

**Comment by Crystal21** [comment]
ya keep profile tab only for student and student tpc

**Comment by pankajsankpal** [comment]
cool i updated the UI as per u said  
its looking like this..
![tpomodified](https://cloud.githubusercontent.com/assets/17172292/15626400/8d1773c2-24e1-11e6-9faf-6c4acdb32a25.png)

if ny changes , do suggest ,.!

**Comment by pankajsankpal** [comment]
at the top right corner , name of the actor that has logged in 
and for student and stu_tpc there will be additional tab as profile

**Comment by ZNevzz** [comment]
@pankajsankpal You're the best :100: / :100:
