### ISSUE TITLE
Directory structure

### ISSUE THREAD

**Issue by ZNevzz** [frcrceinterns/PMS_FINAL_REPO#33]
We need to decide a directory structure for our upoads/ downloads/ archive.
My suggestion is this : 

2016 

> student
> 
> > resume
> > letters
> > certificates
> 
> faculty
> 
> > reference
> > letters
> 
> tpo
> 
> > reference
> > letters
> > reports
> 
> admin
> 
> > archives

**Comment by melwyn95** [comment]
d suggestion is good

**Comment by LeonDsouza** [comment]
I was thinking of something like 
in Linux directory format
/PlacementSystem
-----/2016-2017(Year)
      -----/Users
            ----- Student
                  ----- Resumes,Letters Certs in folders
            ----- Faculty
                  ----- Reference and letters in folders
            ----- TPO
                  ----- References letters reports in folders
            ----- Admin
                  ----- Archives
     -----/System
           ----- Logs
                 ----- Logs will be stored here so Logger.4j i think will be good
           ----- CSV
                 ----- Either streamwise CSV folders or directly upload CSV eitherway will do
           ----- Email
                 ------ Email_Temp directory for attachment which will be deleted after email is sent




Tell me if anything to be subtracted or added.

**Comment by darshgup139** [comment]
this Structure seems decent enough

**Comment by LeonDsouza** [comment]
[DirectoryIssue.txt](https://github.com/frcrceinterns/PMS_FINAL_REPO/files/285974/DirectoryIssue.txt)

**Comment by LeonDsouza** [comment]
If anything to be added or deleted tell me.. besides i need a list of what all is going to be uploaded other than those listed!

**Comment by ZNevzz** [comment]
Ya it's good @LeonDsouza

**Comment by Crystal21** [comment]
keep the same directory structure neon! :smile_cat:

**Comment by cheryl3** [comment]
The structure is good

**Comment by cheryl3** [comment]
An addition is required though. I have an upload function for room allotment (actor:Faculty TPC)

**Comment by LeonDsouza** [comment]
The structure isn't foolproof...it wont work in most cases.. and i know that!!

**Comment by darshgup139** [comment]
The Structure seems quite good if everyone agrees ..we should finalize it

**Comment by ZNevzz** [comment]
As discussed,  we will access directory  of student using year. 

However we also need to mention year data for all other users too, inorder to access the folder for upload and download

**Comment by frcrceinterns** [comment]
Finally, found a logic good enough to generate directories automatically, Have specified it in the LoginController. So, if it's fine, shouldn't be much of a problem. -@Leon

**Comment by LeonDsouza** [comment]
I need to know the places where other parts of DirectoryService are required.So, that other users can also upload and download stuff. I'm sending a pull request. Keeping it on hold until y'al approve. Once, yal approve just merge and it and please read the logic in the comments in login controller. The over-head is 3 KB per load of home page which i think is minimal enough!
