### ISSUE TITLE
Sem 6 marks

### ISSUE THREAD

**Issue by ZNevzz** [frcrceinterns/PMS_FINAL_REPO#36]
Our system uploads student data CSV at beginning of the sem7. However in the course of time,sem6 marks will arrive. So we need to keep another feature where we can delete old version and upload new version. 

Now how does the new upload affect the current database ( when system is already having live data ) is going to be crucial

**Comment by LeonDsouza** [comment]
If the CSV isnt being used currently, then the upload automatically replaces it with the new CSV and all data in the db is filled according to the new CSV.I guess...

**Comment by melwyn95** [comment]
When sem 6 marks arrive only one table needs to be updated i.e. user_schema.qualification.
So, from d new csv file v will only update d DB with qualification.

**Comment by Crystal21** [comment]
yup melwyn is right..
but we gotta auto truncate loader table and qualification table..lots of stuff to think about..
okay i'll start thinking of a way to do this! :smile:

**Comment by ZNevzz** [comment]
We'll have to write code for it @melwyn95 . The current code just takes values from CSV and puts it in 3-4 tables. Right?

**Comment by frcrceinterns** [comment]
ya right so well have to create a new service sort of thing that will take old csv and new csv and compare both and the only extra thing will be sem 6 marks and fire update queries on DB.
this is shit approach, if someone has a better approach well go ahead wid dat
-melwyn95

**Comment by frcrceinterns** [comment]
-melwyn95

**Comment by ZNevzz** [comment]
@melwyn95 Approach is good but time consuming. Instead delete the old version and again execute the same process what was being earlier.

**Comment by Crystal21** [comment]
arre why so much mehnat ? :scream: 
we'll just copy the file to loader and then only take one column from that.. i.e sem6 marks and replace the values in qualification table for only that column!

**Comment by ZNevzz** [comment]
I feel writing a delete file code, and then using the same AddUsersViaCSV module is faster and less mehnat. But if you know how to do it and can code what you said, absolutely no issues with it

**Comment by Crystal21** [comment]
yup i'll try tomorrow.. i'm very sure it will happen

**Comment by LeonDsouza** [comment]
Yea...deleting the file and using same AddUser sounds convenient. No need to code stuff again.just use /copy add user and delete files

**Comment by darshgup139** [comment]
Even I agree with the idea of deleting the old db and again doing the addCSV process..Dropping the table and inserting will be easier than comparing and then inserting..

**Comment by ZNevzz** [comment]
@Crystal21 Please try the scenario : Upload a copy of csv file with sem6 marks blank. Then upload another CSV file with sem6 marks filled.

**Comment by ZNevzz** [comment]
Today ( 6/6/16)  @Crystal21 successfully executed uploading CSV the second time with sem 6 marks and it worked. Hence issue solved
