### ISSUE TITLE
We need to get academic year of user in session

### ISSUE THREAD

**Issue by melwyn95** [frcrceinterns/PMS_FINAL_REPO#37]
We need to get academic year of user in session because 
the directory structure will be year/stu.......
so, ppl some suggestions plz

**Comment by Crystal21** [comment]
why in session mel?
u mean year of passing na?

**Comment by ZNevzz** [comment]
OK. We will set it when he logs in. I'll do it in UpdateProfileController

**Comment by frcrceinterns** [comment]
fine, we need year to access the directory.
so issue is sorted i guess, well make modification in download ka thing dat ill take year from session
-melwyn95

**Comment by ZNevzz** [comment]
It has been set in session successfully
